apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cilium-test

resources:
- namespace.yaml
- config.yaml
- backend-app.yaml
- envoy-config.yaml
- network-policy.yaml
- test-credentials-configmap.yaml

# Common labels applied to all resources
commonLabels:
  managed-by: kustomize
  project: cilium-wasm-test
